### ISSUE TITLE
Fix broken virtual environment

### ISSUE THREAD

**Issue by luccalb** [amosproj/amos2024ws01-rtdip-data-quality-checker#8]
As described by @Timm638 the creation of a virtual environment fails due to missing dependencies.

> The pipeline at the main repo resuses a once built virtual environment. Since we forked the repo, the pipeline has to build a new virtual environment, since no one is cached. Ths fails, since micromamba (a tool for installing conda packages) somehow can't find all packages.

**Acceptance Criteria**

- [ ] The Github Actions run without errors

**Comment by Timm638** [comment]
The issue seems to be that micromamba can't find the moto package. Therefore installing the conda environment fails. ([Job log](https://github.com/amosproj/amos2024ws01-rtdip-data-quality-checker/actions/runs/11441609327/job/31830044663#step:6:71))
I can imagine, that the issue also exists in the main repo, but isn't noticed since they have got an older environment cached.

I've tried updating the moto dependencie to 5.1.4, but that didn't fix the issue. ([Job log](https://github.com/amosproj/amos2024ws01-rtdip-data-quality-checker/actions/runs/11442263623/job/31832218090))

**Comment by dh1542** [comment]
Fixed the issue. Moto needs to be used without the [s3] channel. I edited the environment.yml.
Now only the Sonarqube tests are failing, which is also the case in the rtdip/core repo.

**Comment by dh1542** [comment]
PR: https://github.com/amosproj/amos2024ws01-rtdip-data-quality-checker/pull/12

**Comment by Timm638** [comment]
> Fixed the issue. Moto needs to be used without the [s3] channel. I edited the environment.yml. Now only the Sonarqube tests are failing, which is also the case in the rtdip/core repo.

Some utilities for S3 are dependent on `moto`. The package `moto` [was added as an dependency a year ago](https://github.com/amosproj/amos2024ws01-rtdip-data-quality-checker/commit/9a318b2032aa37bfd4cb1c8a7deee3339b800ef2).
Pulling out the dependency is also a possible solution for the problem, but only if the related code is not needed anymore.

**Comment by dh1542** [comment]
> > Fixed the issue. Moto needs to be used without the [s3] channel. I edited the environment.yml. Now only the Sonarqube tests are failing, which is also the case in the rtdip/core repo.
> 
> Some utilities for S3 are dependent on `moto`. The package `moto` [was added as an dependency a year ago](https://github.com/amosproj/amos2024ws01-rtdip-data-quality-checker/commit/9a318b2032aa37bfd4cb1c8a7deee3339b800ef2). Pulling out the dependency is also a possible solution for the problem, but only if the related code is not needed anymore.


These files run fine with only `moto`. I ran the tests for them. If problems will arise later, we can handle them later but for now this seems like the best solution.

**Comment by Timm638** [comment]
I've debugged the issue with the stage `job_run_unit_tests_and_sonarqube`. There the path of the coverage report at step `Override Coverage Source Path for Sonar` was incorrect. The only issue remaining with the pipeline is the missing `SONAR_TOKEN` secret, which we currently don't have.

When debugging Github Actions, the location of the script has to be set in `develop.yml`, otherwise the file from rtdip/core will be used. I've added a comment for that in the file.
